<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Title>CnCNet Server</Title>
    <Product>CnCNet RS Server</Product>
    <Copyright>Copyright © 2020-2025</Copyright>
    <RootNamespace>CnCNetServer</RootNamespace>
    <AssemblyName>cncnet-server</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ComVisible>false</ComVisible>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <LangVersion>preview</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UseAppHost Condition="'$(RuntimeIdentifier)' == ''">false</UseAppHost>
    <Configurations>Debug;Release;V2AndV3Debug;V2AndV3Release</Configurations>
    <Optimize Condition="'$(Configuration.Contains(Release))'">true</Optimize>
    <DefineConstants Condition="'$(Configuration.Contains(Debug))'">$(DefineConstants);DEBUG</DefineConstants>
    <DefineConstants Condition="'$(Configuration.Contains(V2AndV3))'">$(DefineConstants);EnableLegacyVersion</DefineConstants>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="!$(DefineConstants.Contains('EnableLegacyVersion'))">
    <Compile Remove="CnCNet\Net\Tunnel\TunnelV2.cs" />
  </ItemGroup>
  <ItemGroup Condition="$(DefineConstants.Contains('EnableLegacyVersion'))">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition="!$(DefineConstants.Contains('EnableLegacyVersion'))">
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.7" />
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.7" />
  </ItemGroup>
</Project>